INSERT INTO coin(COIN_NAME, YEAR, DENOMINATION, INCOLLECTION, COIN_DESCRIPTION, COUNTRY) 
VALUES 
('Five Pence', 1995, '£0.05', FALSE, 'Small Silver Looking Coin', 'UK');
INSERT INTO coin(COIN_NAME, YEAR, DENOMINATION, INCOLLECTION, COIN_DESCRIPTION, COUNTRY) 
VALUES 
('Two Pounds', 1997, '£2.00', FALSE, 'The Mightiest Coin of them all!', 'UK');
INSERT INTO coin(COIN_NAME, YEAR, DENOMINATION, INCOLLECTION, COIN_DESCRIPTION, COUNTRY) 
VALUES 
('1 Dollar George Washington Mintmark P', 2008, '$1.00', FALSE, 'Commemorative Coin with Georgie\'s face on it', 'USA');

